---
- hosts: home
  vars:
    username: chris
    public_key: ~/.ssh/id_rsa.pub
  tasks:

    - name: Ensure sudo group is present
      group:
        name: sudo
        state: present

    - name: Ensure sudo group has sudo privileges
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL:ALL) ALL"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Create default user
      user:
        name: "{{ username }}"
        groups: sudo
        #password: "{{ password }}"
        shell: /bin/bash
        update_password: always
        state: present

    - name: Add authorized key
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', public_key ) }}"

    - name: create directory
      ansible.builtin.file:
        path: /mnt/docker
        state: directory
        recurse: yes
        force: no
        owner: root
        group: root
        mode: '0755'

    - name: Creating mount.sh
      copy:
        dest: "/home/chris/mount.sh"
        content: |
          #! /bin/sh
          mount 10.20.200.131:/volume1/docker /mnt/docker

    - name: Changing perm of "/home/chris/mount.sh", adding "+x"
      file: dest=/home/chris/mount.sh mode=a+x

    - name: Adding mount.sh to Crontab
      ansible.builtin.cron:
        name: "Mount Folders at reboot"
        special_time: reboot
        job: "/home/chris/mount.sh"

    - name: Update apt cache and make sure nfs-common is installed
      apt:
         name: nfs-common
         update_cache: yes